[[redirects]]
  from = "/api/*"
  to = "https://www.koreaexim.go.kr/site/program/financial/exchangeJSON"
  status = 200

[[redirects]]
  from = "/"
  to ="/index.html"
  status = 200

  [context.production.environment]
  KEY = "From netlify.toml"
  REACT_APP_KEY = "From netlify.toml (REACT_APP_)"